---
- name: Base configuration for all tiers
  hosts: all
  become: yes
  roles:
    - common
    - ssh-hardening
    - firewall

- name: Configure database tier
  hosts: db
  become: yes
  roles:
    - database

- name: Configure app tier
  hosts: app
  become: yes
  roles:
    - backend

- name: Configure web tier
  hosts: web
  become: yes
  roles:
    - frontend
